version: '3'
services:
  wss:
    hostname: wss
    build:
       dockerfile: Dockerfile-wss
       context: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '7502:7502'

  php:
    hostname: wallet
    depends_on:
      - wss
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '9001:80'
